mother(ann,henry).
mother(ann,mary).
mother(jane,mark).
mother(jane,francis).
mother(annette,jonathan).
mother(mary,bill).
mother(janice,louise).
mother(lucy,janet).
mother(louise,caroline).
mother(caroline,david).
mother(caroline,janet).
father(henry,jonathan).
father(john,mary).
father(francis,william).
father(francis,louise).
father(john,mark).
father(gavin,lucy).
father(john,francis).
parent(victoria,george).
parent(victoria,edward).
parent(X,Y):-mother(X,Y).
parent(X,Y):-father(X,Y).
parent(elizabeth,charles).
parent(elizabeth,andrew).
ancestor(X,Y):-parent(X,Y).
ancestor(X,Y):-parent(X,Z),ancestor(Z,Y).
child_of(A,B):-parent(B,A).
child_of(A,B):-father(B,A),mother(B,A).
grandfather_of(A,B):-father(A,Y),parent(Y,B).
grandmother_of(A,B):-mother(A,Y),parent(Y,B).
great_grandfather_of(A,B):-father(A,Y),grandfather_of(Y,B).
great_grandmother_of(A,B):-mother(A,Y),grandmother_of(Y,B).
sibling_of(M,N):-parent(X,M),parent(X,N).
couples(G,H):-mother(G,X),father(H,X).
